// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4TQv65JAhaRa5dPLQjJ_2QyBhlQLyjSg',
    appId: '1:245333633905:web:7b82958a2fbab40a3ca4d0',
    messagingSenderId: '245333633905',
    projectId: 'motiv8-cfcf1',
    authDomain: 'motiv8-cfcf1.firebaseapp.com',
    storageBucket: 'motiv8-cfcf1.appspot.com',
    measurementId: 'G-GG53N47WX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7C3VQTW7pyFeoCKYSikWbS3gsLmnm3Sg',
    appId: '1:245333633905:android:c47f648dfd68edd73ca4d0',
    messagingSenderId: '245333633905',
    projectId: 'motiv8-cfcf1',
    storageBucket: 'motiv8-cfcf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZxLZmxmAhhicCgRUKzTdnixlHhEBZK8',
    appId: '1:245333633905:ios:6c22075ad96e06613ca4d0',
    messagingSenderId: '245333633905',
    projectId: 'motiv8-cfcf1',
    storageBucket: 'motiv8-cfcf1.appspot.com',
    iosClientId: '245333633905-a2su7c1s2e8d7pn7650sr8pjdm6km5jt.apps.googleusercontent.com',
    iosBundleId: 'com.ezanatesfaye.motiv8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZxLZmxmAhhicCgRUKzTdnixlHhEBZK8',
    appId: '1:245333633905:ios:ca9772c2d7dd97993ca4d0',
    messagingSenderId: '245333633905',
    projectId: 'motiv8-cfcf1',
    storageBucket: 'motiv8-cfcf1.appspot.com',
    iosClientId: '245333633905-fhet4olm7vmrf4c9bseeqmsebq78jhoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.motiv8Ai.RunnerTests',
  );
}
