import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:motiv8_ai/controllers/chat_controllers.dart';
import 'package:motiv8_ai/widgets/custom_appbar.dart';

class GenerateAI extends ConsumerWidget {
  GenerateAI({Key? key}) : super(key: key);
  String motiv8Description = """
Your name is 'MOTIV8-AI'. I want you to act as a motivational coach. I will provide you with some information about someone's goals and challenges, and it will be your job to come up with strategies that can help this person achieve their goals. This could involve providing positive affirmations, giving helpful advice or suggesting activities they can do to reach their end goal. if you don't understand the question, don't think too much, tell the user to be more specific with more details
Motiv8-AI is a mobile app that is designed to help users set and achieve goals by providing daily reminders and motivational messages. The app has several features, including the ability to create and manage multiple goals, track progress, connect with others who have similar goals, and receive personalized motivational messages generated by an AI language model called ChatGPT.

Motiv8-AI also has a goal breakdown screen that allows users to break down their goals into smaller, more manageable tasks. The screen uses ChatGPT to generate a list of suggested tasks based on the user's goal and progress, spread out in the timeline for the user-entered start and end dates. This feature provides users with a personalized and realistic plan to achieve their goals.

In terms of what Motiv8-AI cannot do, it is important to note that the app is not a substitute for professional guidance or medical advice. While the app can provide users with motivation and support, it cannot diagnose or treat any medical conditions or mental health issues. Additionally, the app is not capable of physical activity tracking, such as steps or distance traveled.

Overall, Motiv8-AI is a powerful tool for young adults and professionals who are interested in self-improvement and goal-setting. By understanding the capabilities and limitations of the app, users can get the most out of its features and achieve their goals with greater ease and motivation.
""";
  final _textController = TextEditingController();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ThemeData themeData = Theme.of(context);
    return Scaffold(
      appBar: CustomAppBar(title: 'Chat Motiv8-AI'),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Expanded(
              child: ref.watch(chatAPIControllerProvider).when(
                    loading: () =>
                        const Center(child: CupertinoActivityIndicator()),
                    error: (error, _) => Text('Error: $error',
                        style: themeData.textTheme.bodyLarge),
                    data: (messages) => ListView.builder(
                      itemCount: messages.length,
                      itemBuilder: (context, index) {
                        final message = messages[index];
                        final isUser = message['role'] == 'user';
                        return Container(
                          alignment:
                              isUser ? Alignment.topRight : Alignment.topLeft,
                          child: ConstrainedBox(
                            constraints: BoxConstraints(
                              maxWidth: MediaQuery.of(context).size.width * 0.8,
                            ),
                            child: Card(
                              color: isUser
                                  ? themeData.primaryColorLight
                                  : themeData.secondaryHeaderColor,
                              child: Padding(
                                padding: const EdgeInsets.all(8),
                                child: Text(
                                  message['content'],
                                  style: TextStyle(
                                    color: isUser
                                        ? themeData.primaryColor
                                        : Colors.black,
                                  ),
                                ),
                              ),
                            ),
                          ),
                        );
                      },
                    ),
                  ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _textController,
              decoration: InputDecoration(
                border: InputBorder.none,
                hintText: 'Enter your prompt',
                hintStyle: themeData.textTheme.bodyLarge,
              ),
              onSubmitted: (prompt) {
                if (prompt.isNotEmpty) {
                  ref.read(chatAPIControllerProvider.notifier).sendMessage([
                    {"role": "system", "content": motiv8Description},
                    {"role": "user", "content": prompt},
                  ]);
                  _textController.clear();
                }
              },
            ),
          ],
        ),
      ),
    );
  }
}
